### PR TITLE
Transaction pool improvements

### PR DESCRIPTION
**Pull request by tzdybal**
Transaction pool improvements cherry-picked from ETH geth.

### CODE REVIEW

**Comment by tzdybal** [comment]
Pool size after changes:
txpool

**Comment by lostinblue** [comment]
Makes sense to me, I say we pull this in. I can improve it further too once I have time. Those geth developers are embarrassingly bad, this source is pretty bad from the start. Its really sad they are treated with any respect whatsoever.

**Comment by tzdybal** [comment]
1. This is the wrong repository - wrong organization. Now `ethereumclassic` is official, not `ethereumproject`.
2. This was not merged, as this code, cherry-picked from ETH, has known and fixed bugs in ETH. So it 'mostly works in my environment' stage. The fixes was not incorporated, because of dependency hell related to other changes required by those fixes.

**Comment by tzdybal** [comment]
I'm closing this PR, as it's irrelevant.

**Pull request closed without merging**
