### PR TITLE
[release 1.4.12] core/state: Fix memory expansion bug by not copying …

### PR DESCRIPTION
**Pull request by elaineo**
Checked ok:

* Sync ETC
* Sync ETH

### CODE REVIEW

**Comment by elaineo** [comment]
Let's establish a procedure for releasing builds. @ericsomdahl sholud we use bintray?

**Comment by ericsomdahl** [comment]
@elaineo There are pros and cons to Bintray for a project like Geth.   Setting up Bintray was primarily driven by the desire to have an easy bridge for pushing our version of EthereumJ and etherjar into Maven Central.  Geth doesn't need integration into 3rd party distribution mechanisms... Go/ Godeps seems to natively support github.

Bintray does not provide any advantages over Github as far as being a CDN goes.  A release of geth is unlikely to ever trip any Github bandwidth alarms since there would only ever be a few thousand downloads.

The only advantage I see for using Bintray would be in having a one-stop shop for downloading all ETC artifacts.  Cpp-ethereum isn't being deployed to Bintray.  Pyethereum natively prefers PyPi and would not make sense for Bintray.  Mist is also deployed via Github.  

So that one-stop advantage does not actually exist... is that something we want?  I gathered by the lack of interest in integrating builds into TeamCity that the core devs are happy with how their workflows currently work.

**Comment by mikeyb** [comment]
I am able to get past the block with the naughty code in it with the patch from go-ethereum upstream maintainer @Arachnid (Thank you for your efforts)

I think we should probably make this PR go directly to [master](https://github.com/ethereumproject/go-ethereum/tree/master) and backport it to develop since we have many changes in the `develop` branch that would also need to be merged into `master`.

While I am all for processes and procedures, we do not have the time or capacity to do a proper release in the sense on this issue.

Thoughts?

**Comment by Arachnid** [comment]
I'd suggest doing what we did: PR to develop, and then cherry-pick it to master for a release. That way you won't mess up future releases with changes that are in master but not develop, and you can still push out a release quickly.

**Comment by whatisgravity** [comment]
I can merge it into develop. I will start with a fork local to my account and once I have the merge working I will push it to the development branch on this project. I will cherry pick @Arachnid changes, but it appears we may need to more thoroughly address this issue as the last 4 hot fixes have not satisfactorily solved the DOS issues.

**Comment by mikeyb** [comment]
Looks like we need to apply [this commit](https://github.com/ethereum/go-ethereum/commit/a59a93f476434f2805c8fd3e10bf1b2f579b078f) as well as this is when our state.db file starts to differ greatly and the cause of build failures in 1.4.13+

While the DOS issue is not fixed in these builds, the caching seems to help performance regardless.

**Comment by splix** [comment]
Applied

**Pull request closed without merging**
