### PR TITLE
Update websocket.go to fix websocket origin issue: 

### PR DESCRIPTION
**Pull request by Bunjin**
Cf issue: https://github.com/ethereumproject/go-ethereum/issues/575

### CODE REVIEW

**Comment by whilei** [comment]
The header's field key `Origin` should actually be capitalized (like all the other field keys), per the spec:
- Page 4 of the websocket spec at https://tools.ietf.org/html/rfc6455 
- https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake

If you add a debugging log line right beneath your proposed change
```go
		origin := strings.ToLower(req.Header.Get("Origin"))
		glog.D(logger.Error).Infof("req.Header", req.Header)
		if allowAllOrigins || origins.Has(origin) {
			return nil
		}
```
doing `wscat -c ws://127.0.0.1:8540` (as written #575) you'll see:
```
2018-05-01 08:45:09 req.Header%!(EXTRA http.Header=map[Sec-Websocket-Version:[13] Sec-Websocket-Key:[3pe1k756838Upx9nPlphpg==] Connection:[Upgrade] Upgrade:[websocket] Sec-Websocket-Extensions:[permessage-deflate; client_max_window_bits]])
```
which shows there's  no `Origin` field set at all. 

However, doing 
```
$ wscat --help

  Usage: wscat [options] (--listen <port> | --connect <url>)


  Options:

    -V, --version                 output the version number
    -l, --listen <port>           listen on port
    -c, --connect <url>           connect to a websocket server
    -p, --protocol <version>      optional protocol version
    -o, --origin <origin>         optional origin
    -x, --execute <command>       execute command after connecting
    -w, --wait <seconds>          wait given seconds after executing command
    --host <host>                 optional host
    -s, --subprotocol <protocol>  optional subprotocol
    -n, --no-check                Do not check for unauthorized certificates (default: true)
    -H, --header <header:value>   Set an HTTP header. Repeat to set multiple. (--connect only) (default: )
    --auth <username:password>    Add basic HTTP authentication header. (--connect only)
    --ca <ca>                     Specify a Certificate Authority (--connect only)
    --cert <cert>                 Specify a Client SSL Certificate (--connect only)
    --key <key>                   Specify a Client SSL Certificate's key (--connect only)
    --passphrase [passphrase]     Specify a Client SSL Certificate Key's passphrase (--connect only). If you don't provide a value, it will be prompted for.
    --no-color                    Run without color (default: true)
    -h, --help                    output usage information

$ wscat -o 127.0.0.1 -c ws://127.0.0.1:8540
connected (press CTRL+C to quit)
> exit
```
yields a successful connection, with geth logging:
```shell
2018-05-01 08:46:39 req.Header%!(EXTRA http.Header=map[Sec-Websocket-Version:[13] Sec-Websocket-Key:[5NrvL0Cur+K16pWAL0aSaA==] Connection:[Upgrade] Upgrade:[websocket] Sec-Websocket-Extensions:[permessage-deflate; client_max_window_bits] Origin:[127.0.0.1]])
```

**Comment by splix** [comment]
I was playing with WS for some time recently. Had some issues actually, but all related to other things. Can confirm that capitalized header works fine with other clients

**Comment by whilei** [comment]
Closing since this is user/+tooling issue, not a geth problem.

**Comment by Bunjin** [comment]
Hey guys, thanks,

So yes actually this was a problem with web3 which doesn't set the origin.
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-ws/src/index.js#L78

I changed undefined to 127.0.0.1 and it worked :+1: 

https://github.com/websockets/ws

**Pull request closed without merging**
