### PR TITLE
Refactor: use JSON for default chain configs

### PR DESCRIPTION
**Pull request by whilei**
Share JSON config parsing functions between both custom and default chain configurations. Moves default chain configuration out of Go code and into `/core/config/*.json` (removes files `/core/data_chainconfig.go`, `/core/data_genesis.go`, and `cmd/geth/boot.go`).

In order to include external JSON resources in geth binary build requires compiling these JSON assets, as below. Default JSON assets should be compiled anytime they change.

```bash
# Install program to include external JSON files as binary resources
go get github.com/omeid/go-resources/cmd/resources
# Compile JSON to assets package (whichs avoids extra unnecessary recompilation when building for other changes because go will use the compile cache becuase it's in a package)
resources -declare -var=DEFAULTS -package=assets -output=core/assets/assets.go core/config/*.json
```

Default tests to ensure backwards compatibility for default chain configs are in `/core/defaults_test.go`.

Rel #342

### CODE REVIEW

**Comment by whilei** [comment]
(just documenting): Possibly issue on AppVeyor with JSON-(re)compilation double-check/forgetfulness-insurance -- 

```
go get github.com/omeid/go-resources/cmd/resources
resources -declare -var=DEFAULTS -package=assets -output=core/assets/assets.go core/config/*.json
2017/09/13 13:41:50 Finished in 261.0261ms. Wrote 2 resources to core/assets/assets.go
go test ./...
# github.com/ethereumproject/go-ethereum/core/assets
core\assets\assets.go:140:11: unknown escape sequence
core\assets\assets.go:92927:6: duplicate key "" in map literal
core\assets\assets.go:92927:13: unknown escape sequence
ok  	github.com/ethereumproject/go-ethereum/accounts	10.241s
ok  	github.com/ethereumproject/go-ethereum/accounts/abi	0.058s
ok  	github.com/ethereumproject/go-ethereum/accounts/abi/bind	0.117s
```
https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.662

**Comment by splix** [comment]
Can we generate it just on compile step? from travis/appveyor

**Comment by whilei** [comment]
I would rather do it that way too, but I wound up including the compiled assets because

1. not including them means adding a couple steps/dependencies for anyone wanting to build from source -- I wanted to avoid this to keep it as simple as possible for end-users/developers

2. the above issue with `go-resources` on AppVeyor generating invalid code -- I'll submit an issue to that project and see if we can get it resolved to keep our options open

**Comment by splix** [comment]
It's a bad practice to keep something that can be generated from existing code. But there I don't know what to do. Usually you have a build system, like npm, grunt, webpack, cargo, maven, gradle, makefile, etc. But afaik golang idea that project should work without any build system, just from a github url. So you have a choice: a) violate idiomatic golang and introduce a makefile or b) store generated artifacts with source code.

**Comment by whilei** [comment]
Yea, I would rather keep the artifact out of the source, too... unfortunately for now it seems like the simplest option, which is why I'm leaning toward it.

Keeping an eye on https://github.com/omeid/go-resources/issues/12, which is a block for building on Windows with my preferred `go-resources` package, and if/when that issue is resolved I can further explore solutions around removing the artifacts from the source and either makefile or revise the instructions for building from source. (We could also provide an alternative link to the config artifact.)

**Comment by whilei** [comment]
Going to go ahead and merge, noting the final issue #351 as the only remaining loose-end.

**Pull request merged**
