### PR TITLE
1.4.11 stable

### PR DESCRIPTION
**Pull request by elaineo**
Trying to get a clean build to work from.

The only change since 1.4.10 is the ETH hotfix to fix the memory leak, with added comments to the best of my ability

Also removed the dao_test so all tests pass.

### CODE REVIEW

**Comment by elaineo** [comment]
I gave up on trying to get all the tests working on the most up-to-date version, so I applied the memory-leak patch to the last stable release. If @whatisgravity returns, or if someone else wants to take a stab at it, we can merge all the subsequent changes back in, but right now we should have a build release that passes all the tests.

**Comment by elaineo** [comment]
I'd like to send this straight to a release. I don't see the point of merging it into develop since develop is currently unstable.

**Comment by splix** [comment]
@elaineo ok, that's probably a good idea

**Comment by mikeyb** [comment]
I don't see an issue merging to develop.  This change doesnt affect anything currently out of sync in develop.  We can cherry pick the commit like arachnid suggested to master and promote into a release that way while still retaining the fix in develop in case we decide to stick with develop branch

**Pull request merged**
