### PR TITLE
'--chain=testnet' should configure testnet

### LINKED ISSUE #226: Uses mainnet config for testnet
```
$ ./geth --chain testnet --datadir chains/geth-master
I0511 08:02:56.561248 ethdb/database.go:63] Alloted 128MB cache and 1024 file handles to chains/geth-master/testnet/chaindata
I0511 08:02:56.576481 cmd/geth/flag.go:700] Did read chain configuration from database: chains/geth-master/testnet/chaindata
I0511 08:02:56.578893 cmd/geth/flag.go:780] Loading mainnet configuration from database with genesis block 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3.
I0511 08:02:56.579149 cmd/geth/flag.go:747] --------------------------------------------------------------------------------------------------------------
I0511 08:02:56.579175 cmd/geth/flag.go:749] Starting Geth Classic v3.3.193+3ed472a
I0511 08:02:56.579203 cmd/geth/flag.go:750] Geth is configured to use blockchain: testnet (ETC)
I0511 08:02:56.579220 cmd/geth/flag.go:752] 4 blockchain upgrades associated with this configuration:
I0511 08:02:56.579244 cmd/geth/flag.go:755]  1150000 Homestead
I0511 08:02:56.579259 cmd/geth/flag.go:755]  1920000 The DAO Hard Fork
I0511 08:02:56.579290 cmd/geth/flag.go:757]          with block 0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f
I0511 08:02:56.579306 cmd/geth/flag.go:755]  2500000 GasReprice
I0511 08:02:56.579320 cmd/geth/flag.go:755]  3000000 Diehard
```

### PR DESCRIPTION
**Pull request by whilei**
Sensible use case.

Fixes #226

### CODE REVIEW

**Comment by whilei** [comment]
@splix I thought it might be confusing for `--chain=testnet` to use _/testnet_ subdirectory, while `--testnet` and `--chain=morden` use _/morden_, so made them all use _/morden_.  See f5e45c1.

**Comment by splix** [comment]
Yes, right. Thank you. Also wanted to ask to configure them to use /morden dir. Because we could support other testnets, like Ropsten/Kovan/Rinkeby testnets, each in own subdir

**Comment by whilei** [comment]
79d65fa makes it so `--testnet` can override _configuration_ (but not subdir location) iff `--chain` is _not_ "morden" or "testnet". 

... It might be easiest to show, rather than tell :wink: 
```bash
# Ensure --testnet and --chain=morden/testnet set up respective subdirs with default 'morden'
@test "--chain=testnet creates /morden subdir, activating testnet genesis" { # This is kind of weird, but it is expected (and better than encouraging accidentally setting up two testdata subdirs).
	run $GETH_CMD --data-dir $DATA_DIR --chain=testnet --exec 'eth.getBlock(0).hash' console
	[ "$status" -eq 0 ]

	[[ "$output" == *"0x0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303"* ]]

	[ -d $DATA_DIR/morden ]
}

@test "--testnet creates /morden subdir, activating testnet genesis" {
	run $GETH_CMD --data-dir $DATA_DIR --testnet --exec 'eth.getBlock(0).hash' console
	[ "$status" -eq 0 ]
	[[ "$output" == *"0x0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303"* ]]

	[ -d $DATA_DIR/morden ]
}

@test "--testnet --chain=faketestnet creates /faketestnet subdir, activating testnet genesis" {
	run $GETH_CMD --data-dir $DATA_DIR --testnet --chain=faketestnet --exec 'eth.getBlock(0).hash' console
	[ "$status" -eq 0 ]
	[[ "$output" == *"0x0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303"* ]]

	[ -d $DATA_DIR/faketestnet ]
}

@test "--chain=morden creates /morden subdir, activating testnet genesis" {
	run $GETH_CMD --data-dir $DATA_DIR --chain=morden --exec 'eth.getBlock(0).hash' console
	[ "$status" -eq 0 ]
	[[ "$output" == *"0x0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303"* ]]

	[ -d $DATA_DIR/morden ]
}
```

**Comment by splix** [comment]
Yeah, I'm referring to:
> so made them all use /morden

👍

**Pull request merged**
