### PR TITLE
cmd/geth: implement status

### LINKED ISSUE #215: Create status command
Make it possible to use `$ geth status` to get an overview status of blockchain, including:
 - Latest blocks (fast, full, headers), and if caught up (or close?) to latest
 - chaindata db path
 - configuration specs (fork, eip/ecips in use)

... basically a comprehensive-ish++ output of chain status like what you see when you just run the geth node, but without having to run-and-quit a node.

### PR DESCRIPTION
**Pull request by odeke-em**
Fixes #215.

Prints out the status of the current node without
having to run and then stop the node.

* Exhibit:
```shell
$ geth status
I0523 23:53:42.934039 ethdb/database.go:63] Alloted 128MB cache and 1024
file handles to
/Users/emmanuelodeke/Library/EthereumClassic/mainnet/chaindata
I0523 23:53:42.937428 cmd/geth/flag.go:788] Did read chain configuration
from
0523 23:53:42.937443 cmd/geth/flag.go:868] Loading
innetdatabase:ers/emmanuelodeke/Lition from database...
I0523 23:53:42.937615 cmd/geth/flag.go:835]
--------------------------------------------------------------------------------------------------------------
I0523 23:53:42.937622 cmd/geth/flag.go:837] Starting Geth Classic
brary/EthereumClassic/mainnet/chaindata
0523 23:53:42.937624 cmd/geth/flag.go:838] Geth is configured to use
0523 23:53:42.937628 cmd/geth/flag.go:840] 4 blockchain upgrades
associated with this configuration:
I0523 23:53:42.937637 cmd/geth/flag.go:843]  1150000 Homestead
I0523 23:53:42.937642 cmd/geth/flag.go:843]  1920000 The DAO Hard Fork
I0523 23:53:42.937648 cmd/geth/flag.go:845]          with block
0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f
I0523 23:53:42.937652 cmd/geth/flag.go:843]  2500000 GasReprice
I0523 23:53:42.937655 cmd/geth/flag.go:843]  3000000 Diehard
I0523 23:53:42.937659 cmd/geth/flag.go:855]
--------------------------------------------------------------------------------------------------------------
I0523 23:53:42.937751 cmd/geth/flag.go:335] WARNING: No etherbase set
and no accounts found as default
I0523 23:53:45.233246 cmd/geth/main.go:267] (*node.Node)(0xc4200c0500)({
 datadir: (string) (len=52)
"/Users/emmanuelodeke/Library/EthereumClassic/mainnet",
 eventmux: (*event.TypeMux)(0xc420100d80)({
  mutex: (sync.RWMutex) {
   w: (sync.Mutex) {
    state: (int32) 0,
    sema: (uint32) 0
   },
   writerSem: (uint32) 0,
   readerSem: (uint32) 0,
   readerCount: (int32) 0,
   readerWait: (int32) 0
  },
  subm: (map[reflect.Type][]*event.muxsub) <nil>,
  stopped: (bool) false
 }),
 serverConfig: (p2p.Config) {
  PrivateKey: (*ecdsa.PrivateKey)(0xc420100c60)({
   PublicKey: (ecdsa.PublicKey) {
    Curve: (*secp256k1.BitCurve)(0xc420017080)({
     P:
(*big.Int)(0xc42000cf00)(115792089237316195423570985008687907853269984665640564039457584007908834671663),
     N:
(*big.Int)(0xc42000cf40)(115792089237316195423570985008687907852837564279074904382605163141518161494337),
     B: (*big.Int)(0xc42000cf80)(7),
     Gx:
(*big.Int)(0xc42000cfc0)(55066263022277343669578718895168534326250603453777594175500187360389116729240),
     Gy:
(*big.Int)(0xc42000d000)(32670510020758816978083085130507043184471273380659243275938904335757337482424),
     BitSize: (int) 256
    }),
    X:
(*big.Int)(0xc42011ea20)(49631543432364056475079206909261186057181347752541209639221940900049586264550),
    Y:
(*big.Int)(0xc42011ea80)(63627346344724849694388614251809059400434334735548537341482816020963557886370)
   },
   D:
(*big.Int)(0xc42011e9c0)(99793846405704554899783237505447401757778173893323734693982066754995055962197)
  }),
  MaxPeers: (int) 25,
  MaxPendingPeers: (int) 0,
  Discovery: (bool) true,
  Name: (string) (len=26) "Geth/source/darwin/go1.8.1",
  BootstrapNodes: ([]*discover.Node) (len=9 cap=9) {
   (*discover.Node)(0xc4202a8b80)(enode://e809c4a2fec7daed400e5e28564e23693b23b2cc5a019b612505631bbe7b9ccf709c1796d2a3d29ef2b045f210caf51e3c4f5b6d3587d43ad5d6397526fa6179@174.112.32.157:30303),
   (*discover.Node)(0xc4202a8d00)(enode://6e538e7c1280f0a31ff08b382db5302480f775480b8e68f8febca0ceff81e4b19153c6f8bf60313b93bef2cc34d34e1df41317de0ce613a201d1660a788a03e2@52.206.67.235:30303),
   (*discover.Node)(0xc4202a8e80)(enode://5fbfb426fbb46f8b8c1bd3dd140f5b511da558cd37d60844b525909ab82e13a25ee722293c829e52cb65c2305b1637fa9a2ea4d6634a224d5f400bfe244ac0de@162.243.55.45:30303),
   (*discover.Node)(0xc4202a9000)(enode://42d8f29d1db5f4b2947cd5c3d76c6d0d3697e6b9b3430c3d41e46b4bb77655433aeedc25d4b4ea9d8214b6a43008ba67199374a9b53633301bca0cd20c6928ab@104.155.176.151:30303),
   (*discover.Node)(0xc4202a9180)(enode://814920f1ec9510aa9ea1c8f79d8b6e6a462045f09caa2ae4055b0f34f7416fca6facd3dd45f1cf1673c0209e0503f02776b8ff94020e98b6679a0dc561b4eba0@104.154.136.117:30303),
   (*discover.Node)(0xc4202a9300)(enode://72e445f4e89c0f476d404bc40478b0df83a5b500d2d2e850e08eb1af0cd464ab86db6160d0fde64bd77d5f0d33507ae19035671b3c74fec126d6e28787669740@104.198.71.200:30303),
   (*discover.Node)(0xc4202a9480)(enode://5cd218959f8263bc3721d7789070806b0adff1a0ed3f95ec886fb469f9362c7507e3b32b256550b9a7964a23a938e8d42d45a0c34b332bfebc54b29081e83b93@35.187.57.94:30303),
   (*discover.Node)(0xc4202a9600)(enode://39abab9d2a41f53298c0c9dc6bbca57b0840c3ba9dccf42aa27316addc1b7e56ade32a0a9f7f52d6c5db4fe74d8824bcedfeaecf1a4e533cacb71cf8100a9442@144.76.238.49:30303),
   (*discover.Node)(0xc4202a9780)(enode://f50e675a34f471af2438b921914b5f06499c7438f3146f6b8936f1faeb50b8a91d0d0c24fb05a66f05865cd58c24da3e664d0def806172ddd0d4c5bdbf37747e@144.76.238.49:30306)
  },
  StaticNodes: ([]*discover.Node) <nil>,
  TrustedNodes: ([]*discover.Node) <nil>,
  NodeDatabase: (string) (len=58)
"/Users/emmanuelodeke/Library/EthereumClassic/mainnet/nodes",
  Protocols: ([]p2p.Protocol) <nil>,
  ListenAddr: (string) (len=6) ":30303",
  NAT: (*nat.autodisc)(0xc42009a0c0)(UPNP IGDv1-IP1),
  Dialer: (*net.Dialer)(<nil>),
  NoDial: (bool) false
 },
 server: (*p2p.Server)(<nil>),
 serviceFuncs: ([]node.ServiceConstructor) (len=1 cap=1) {
  (node.ServiceConstructor) 0x48f3d80
 },
 services: (map[reflect.Type]node.Service) <nil>,
 rpcAPIs: ([]rpc.API) <nil>,
 inprocHandler: (*rpc.Server)(<nil>),
 ipcEndpoint: (string) (len=61)
"/Users/emmanuelodeke/Library/EthereumClassic/mainnet/geth.ipc",
 ipcListener: (net.Listener) <nil>,
 ipcHandler: (*rpc.Server)(<nil>),
 httpHost: (string) "",
 httpPort: (int) 8545,
 httpEndpoint: (string) "",
 httpWhitelist: ([]string) (len=3 cap=3) {
  (string) (len=3) "eth",
  (string) (len=3) "net",
  (string) (len=4) "web3"
 },
 httpCors: (string) "",
 httpListener: (net.Listener) <nil>,
 httpHandler: (*rpc.Server)(<nil>),
 wsHost: (string) "",
 wsPort: (int) 8546,
 wsEndpoint: (string) "",
 wsWhitelist: ([]string) (len=3 cap=3) {
  (string) (len=3) "eth",
  (string) (len=3) "net",
  (string) (len=4) "web3"
 },
 wsOrigins: (string) "",
 wsListener: (net.Listener) <nil>,
 wsHandler: (*rpc.Server)(<nil>),
 stop: (chan struct {}) <nil>,
 lock: (sync.RWMutex) {
  w: (sync.Mutex) {
   state: (int32) 0,
   sema: (uint32) 0
  },
  writerSem: (uint32) 0,
  readerSem: (uint32) 0,
  readerCount: (int32) 0,
  readerWait: (int32) 0
 }
})
blockchain: urclassic Mainnet (ETC)
```

### CODE REVIEW

**Comment by whilei** [comment]
Check it: https://github.com/odeke-em/go-ethereum/pull/1

**Comment by odeke-em** [comment]
@whilei thanks, just seeing this.

**Comment by whilei** [comment]
Closing in lieu of #251

**Pull request closed without merging**
