### PR TITLE
EXP reprice, ECIP-1015

### PR DESCRIPTION
**Pull request by splix**
Maybe will require additional commits, but ready for review

### CODE REVIEW

**Comment by arvicco** [comment]
I think EXP reprice is not part of ECIP-1015. In ETH, it has a separate EIP-160: https://github.com/ethereum/EIPs/issues/160

**Comment by splix** [comment]
I thought ECIP-1015 is separate, so we can include both EIP-150 and EIP-160 into it, can't we?

**Comment by colibry545** [comment]
We probably need to finish ECIP-1015. For the moment it’s in 'Issues'

**Comment by splix** [comment]
It seems that we're postponing that

**Pull request merged**
