### PR TITLE
Additional ATXI API functions

### PR DESCRIPTION
**Pull request by tzdybal**
Additional functions to manage ATXI build:
* `geth_buildATXI` to start building process
    params:
    * `start` - number of first block to index (`MaxUint64` for "unspecified" value - continue building from last checkpoint)
    * `stop` - number of last block to index (`MaxUint64` for "unspecified" value)
    * `step`- size of a batch
* `geth_getATXIBuildStatus` for status monitoring, returns something like:
    ```
    {
      Current: 250000,
      Start: 0,
      Stop: 500200 
    }
    ```
    If `Current == Stop`, build process finished.

@belfordz, @shanejonas - does the new API make sense to you?

### CODE REVIEW

**Comment by whilei** [comment]
I'm not real keen on using `MaxUint64`, since that will be rather foreign, I expect, for most users. Perhaps instead `null`? `stop` could also be made to use the `TAG` parameter type suggested in #596. 

And maybe a default value if `step` gets a `null` value?

**Comment by whilei** [comment]
Does it make sense to include a param for `buildATXI` to signal to _stop_ building?

**Comment by tzdybal** [comment]
Do we really need this? If you want to have good control of build process you could do it part by part.

**Comment by BelfordZ** [comment]
@whilei @tzdybal If running `./geth --atxi` builds the indexes as well as boots geth, then we will never need to call this RPC. 

While fine grained control over syncing the index might be useful to some, we would love for the `--atxi` command to handle building the indexes internally. IMO the only thing we *may* need an rpc for is checking the status of this indexing processes. 

The reason we are having troubles as it currently stands is that you cannot run 2 instances of geth attached to the same chain db at the same time. We currently must run `./geth atxi-build` before booting geth, which for some may take hours to complete, leaving them on a loading screen for that duration. Once completed, we can then run `./geth --atxi ...`, and from this point as new blocks arrive they are written to the index. 

As a desired alternative, running `./geth --atxi ...` will do both. It will sync new blocks as they come in, while background running the exact same thing that the `./geth atxi-build` command does. Once this is happening, our need to call an rpc to update the index will be no more.

**Comment by shanejonas** [comment]
👍

**Comment by whilei** [comment]
Just an updated example use/output:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"geth_getAddressTransactions","params":["0x68c475c96bc4f771a735037daa70eb97d13d5703", 0, "latest", "tf", "sc", 0, -1, true],"id":1}'
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    "0x4bef1a8f393731b8d77cf3f5157b42f49c9e9cdb330ad7032ffadfa5c6ae06aa",
    "0x65bdd6d803600807b84ee53c00edfc371078eb59cbc9357094452704ef0eb662"
  ]
}
```

```
{"jsonrpc":"2.0","method":"geth_getTransactionsByAddress","params":["0x68c475c96bc4f771a735037daa70eb97d13d5703", 0, 0, "tf", "sc", -1, -1, true],"id":1}
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    "0x4bef1a8f393731b8d77cf3f5157b42f49c9e9cdb330ad7032ffadfa5c6ae06aa",
    "0x65bdd6d803600807b84ee53c00edfc371078eb59cbc9357094452704ef0eb662"
  ]
}
```

```
{"jsonrpc":"2.0","method":"geth_getATXIBuildStatus","params":[],"id":1}
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "Start": 5815000,
    "Stop": 5895904,
    "Current": 5835000,
    "LastError": null
  }
}
```

**Pull request merged**
