### PR TITLE
Standardise Build

### PR DESCRIPTION
**Pull request by pascaldekloe**

### CODE REVIEW

**Comment by ericsomdahl** [comment]
I do enjoy a good round of code deletion!  This all seems fine, and in line with moving to Travis CI

A few questions regarding the final outcome of this process:

- Will we continue to deploy build artifacts to Bintray?
- Will we continue to provide a Windows artifact? Perhaps I am wrong but my recollection is that Travis does not provide a Windows environment... See [Travis CI docs](https://docs.travis-ci.com/user/multi-os/) 

Perhaps [Karalabe's Cross Compiler](https://github.com/karalabe/xgo) would be useful.  It is how the upstream guys build their various targets.  Appveyor does provide a Windows build environment but they don't have an OSX build target -- and using 2 CI systems is not in line with the goal of simplicity  😄

**Comment by pascaldekloe** [comment]
@splix would like to see the unit tests run on different platforms too @ericsomdahl.

Bintray looks kind of cool yet we also publish releases on GitHub. Let's keep one. Do you have favorites?

**Comment by realcodywburns** [comment]
Iirc the ppa, dockers images, and azure templates pull from git hub. Cleaning out the glut is appreciated.

**Comment by ericsomdahl** [comment]
@pascaldekloe: The artifacts found on Github are uploaded manually by @splix when he has created releases, based on items from Bintray

@realcodywburns  The PPA is pushed from TeamCity but that can be changed

**Pull request merged**
