### PR TITLE
m3/3 - mlog headerchain (fast sync), dl.sync data points, and general improvements

### PR DESCRIPTION
**Pull request by whilei**
- Add mlog data points for downloader sync and fast sync (see appendix below)
- Change default max log file size from `1GB` -> `1MB`
- Implement time-interval-based log file rotation for mlog files, default to every 10 minutes (about 10MB per file, ish)
- Allow `--mlog-components=!state,discover` to disable components `state` and `discover`, leaving the other by-default-enabled components still enabled (and still unchanged, `--mlog-components=state,discover` enables _only_ `state` and `discover` components)
- Use pointer values for mlog line vars, enabling to change inside of iteration if ever needed.

- Log `session` value with each mlog line, no matter the format (I think this change may also be included in #503...)
- Log `component` value with mlog line, no matter the format

- Refactor UDP/TCP mapping logging for consistency (9e2c011)

Please note this is requested to merge <- `pr/build-version`, but once that goes in to master, this can merge to master too under either a new PR or changed base (if that's possible). 
This PR primarily intended to propose changes legibly and with some degree of focus.

Rel #494 
Should be merged after #503 

#### Appendix

_Added or modified mlog API fields._

[client]

- [client.start.session](#client-start-session)
- [client.stop.session](#client-stop-session)

----

#### CLIENT START SESSION
Called when the geth client starts up.

__Key value__:
```
2018/02/12 18:00:09 [client] session=MJMofOTo CLIENT START SESSION client.server_id=$STRING client.server_name=$STRING client.server_enode=$STRING client.server_ip=$STRING client.server_maxpeers=$INT client.config_chainname=$QUOTEDSTRING client.config_chainid=$INT client.config_network=$INT client.mlog_components=$STRING client.identity=$OBJECT
```

__JSON__:
```json
{"client.config_chainid":0,"client.config_chainname":"string with spaces","client.config_network":0,"client.identity":{"head":"363c8e0d","version":"","host":"mh","user":"ia","machineid":"a2c2f59f","goos":"darwin","goarch":"amd64","goversion":"go1.9.2","pid":37852,"session":"MJMofOTo"},"client.mlog_components":"string","client.server_enode":"string","client.server_id":"string","client.server_ip":"string","client.server_maxpeers":0,"client.server_name":"string","component":"client","event":"client.start.session","session":"MJMofOTo","ts":"2018-02-12T18:00:09.182144589+09:00"}
```

__Plain__:
```
2018/02/12 18:00:09 [client] MJMofOTo CLIENT START SESSION $STRING $STRING $STRING $STRING $INT $QUOTEDSTRING $INT $INT $STRING $OBJECT
```

_10 detail values_:

- `client.server_id`: $STRING
- `client.server_name`: $STRING
- `client.server_enode`: $STRING
- `client.server_ip`: $STRING
- `client.server_maxpeers`: $INT
- `client.config_chainname`: $QUOTEDSTRING
- `client.config_chainid`: $INT
- `client.config_network`: $INT
- `client.mlog_components`: $STRING
- `client.identity`: $OBJECT

----

#### CLIENT STOP SESSION
Called when the geth client shuts down because of an interceptable signal, eg. SIGINT.

__Key value__:
```
2018/02/12 18:00:09 [client] session=MJMofOTo CLIENT STOP SESSION client.server_id=$STRING client.server_name=$STRING client.server_enode=$STRING client.server_ip=$STRING client.server_maxpeers=$INT client.config_chainname=$QUOTEDSTRING client.config_chainid=$INT client.config_network=$INT client.mlog_components=$STRING client.identity=$OBJECT stop.signal=$STRING stop.error=$STRING_OR_NULL client.duration=$INT
```

__JSON__:
```json
{"client.config_chainid":0,"client.config_chainname":"string with spaces","client.config_network":0,"client.duration":0,"client.identity":{"head":"363c8e0d","version":"","host":"mh","user":"ia","machineid":"a2c2f59f","goos":"darwin","goarch":"amd64","goversion":"go1.9.2","pid":37852,"session":"MJMofOTo"},"client.mlog_components":"string","client.server_enode":"string","client.server_id":"string","client.server_ip":"string","client.server_maxpeers":0,"client.server_name":"string","component":"client","event":"client.stop.session","session":"MJMofOTo","stop.error":null,"stop.signal":"string","ts":"2018-02-12T18:00:09.182604169+09:00"}
```

__Plain__:
```
2018/02/12 18:00:09 [client] MJMofOTo CLIENT STOP SESSION $STRING $STRING $STRING $STRING $INT $QUOTEDSTRING $INT $INT $STRING $OBJECT $STRING $STRING_OR_NULL $INT
```

_13 detail values_:

- `client.server_id`: $STRING
- `client.server_name`: $STRING
- `client.server_enode`: $STRING
- `client.server_ip`: $STRING
- `client.server_maxpeers`: $INT
- `client.config_chainname`: $QUOTEDSTRING
- `client.config_chainid`: $INT
- `client.config_network`: $INT
- `client.mlog_components`: $STRING
- `client.identity`: $OBJECT
- `stop.signal`: $STRING
- `stop.error`: $STRING_OR_NULL
- `client.duration`: $INT

----

[downloader]

- [downloader.register.peer](#downloader-register-peer)
- [downloader.unregister.peer](#downloader-unregister-peer)
- [downloader.tune.qos](#downloader-tune-qos)
- [downloader.start.sync](#downloader-start-sync)
- [downloader.stop.sync](#downloader-stop-sync)

#### DOWNLOADER START SYNC
Called when the downloader initiates synchronisation with a peer.

__Key value__:
```
2018/02/12 17:57:55 [downloader] session=qnCvoOyK DOWNLOADER START SYNC downloader.mode=$STRING sync.peer_id=$STRING sync.peer_name=$STRING sync.peer_version=$NUMBER sync.hash=$STRING sync.td=$BIGINT
```

__JSON__:
```json
{"component":"downloader","downloader.mode":"string","event":"downloader.start.sync","session":"qnCvoOyK","sync.hash":"string","sync.peer_id":"string","sync.peer_name":"string","sync.peer_version":null,"sync.td":0,"ts":"2018-02-12T17:57:55.703887302+09:00"}
```

__Plain__:
```
2018/02/12 17:57:55 [downloader] qnCvoOyK DOWNLOADER START SYNC $STRING $STRING $STRING $NUMBER $STRING $BIGINT
```

_6 detail values_:

- `downloader.mode`: $STRING
- `sync.peer_id`: $STRING
- `sync.peer_name`: $STRING
- `sync.peer_version`: $NUMBER
- `sync.hash`: $STRING
- `sync.td`: $BIGINT

----

#### DOWNLOADER STOP SYNC
Called when the downloader terminates synchronisation with a peer. If ERROR is null, synchronisation was sucessful.

__Key value__:
```
2018/02/12 17:57:55 [downloader] session=qnCvoOyK DOWNLOADER STOP SYNC downloader.mode=$STRING sync.peer_id=$STRING sync.peer_name=$STRING sync.peer_version=$NUMBER sync.peer_hash=$STRING sync.peer_td=$BIGINT sync.pivot=$NUMBER sync.origin=$NUMBER sync.height=$NUMBER sync.elapsed=$DURATION sync.err=$STRING_OR_NULL
```

__JSON__:
```json
{"component":"downloader","downloader.mode":"string","event":"downloader.stop.sync","session":"qnCvoOyK","sync.elapsed":63042000000,"sync.err":null,"sync.height":null,"sync.origin":null,"sync.peer_hash":"string","sync.peer_id":"string","sync.peer_name":"string","sync.peer_td":0,"sync.peer_version":null,"sync.pivot":null,"ts":"2018-02-12T17:57:55.704062836+09:00"}
```

__Plain__:
```
2018/02/12 17:57:55 [downloader] qnCvoOyK DOWNLOADER STOP SYNC $STRING $STRING $STRING $NUMBER $STRING $BIGINT $NUMBER $NUMBER $NUMBER $DURATION $STRING_OR_NULL
```

_11 detail values_:

- `downloader.mode`: $STRING
- `sync.peer_id`: $STRING
- `sync.peer_name`: $STRING
- `sync.peer_version`: $NUMBER
- `sync.peer_hash`: $STRING
- `sync.peer_td`: $BIGINT
- `sync.pivot`: $NUMBER
- `sync.origin`: $NUMBER
- `sync.height`: $NUMBER
- `sync.elapsed`: $DURATION
- `sync.err`: $STRING_OR_NULL

----

#### REMOTE_AGENT SUBMIT WORK
Called when a remote agent submits work to the miner. Note that this method only
acknowledges that work was indeed submitted, but does not confirm nor deny that the PoW was correct.

__Key value__:
```
2018/02/28 16:47:20 [miner] session=hAEs REMOTE_AGENT SUBMIT WORK work.nonce=$INT work.mix_digest=$STRING work.hash=$STRING work.exists=$BOOL
```

__JSON__:
```json
{"component":"miner","event":"remote_agent.submit.work","session":"hAEs","ts":"2018-02-28T16:47:20.548344997+09:00","work.exists":true,"work.hash":"string","work.mix_digest":"string","work.nonce":0}
```

__Plain__:
```
2018/02/28 16:47:20 [miner] hAEs REMOTE_AGENT SUBMIT WORK $INT $STRING $STRING $BOOL
```

_4 detail values_:

- `work.nonce`: $INT
- `work.mix_digest`: $STRING
- `work.hash`: $STRING
- `work.exists`: $BOOL

----

### CODE REVIEW

**Comment by tzdybal** [comment]
LGTM

---

Reviewed 1 of 1 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[.circleci/config.yml, line 68 at r2](https://reviewable.io:443/reviews/ethereumproject/go-ethereum/504#-L5k3kXWCNJFYjcZdXMG:-L5k3kXXqYXW659v-KwD:b2qml0n) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8dec486dd019b9438304276c5c3510fd1b175b57/.circleci/config.yml#L68)):*
> ```YAML
>               export CGO_LDFLAGS="$CGO_LDFLAGS -lresolv"
>             else
>               export EXT_LD_FLAGS="-extldflags=-static"
> ```

This is a cherry pick, right?

---

*[logger/sys.go, line 26 at r2](https://reviewable.io:443/reviews/ethereumproject/go-ethereum/504#-L5k8-zsxcsikqQ4b__y:-L5k8-zsxcsikqQ4b__z:b-8nax9u) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8dec486dd019b9438304276c5c3510fd1b175b57/logger/sys.go#L26)):*
> ```Go
> 
> // mlogLogRollIntervalDefault determines how often mlog files should roll
> const mlogLogRollIntervalDefault = 10 * time.Minute
> ```

Is there any reason to make it configurable? What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ethereumproject/go-ethereum/504#-:-L5kDzB8sYuV1mzAtGw7:bb6ywmx)*

**Comment by whilei** [comment]
*[logger/sys.go, line 26 at r2](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L5k8-zsxcsikqQ4b__y:-L5r1zW42Dl4gKumpSPP:b-d72gxd) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8dec486dd019b9438304276c5c3510fd1b175b57/logger/sys.go#L26)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Is there any reason to make it configurable? What do you think?
</blockquote></details>

I think in the future it might be a nice-to-have feature, but for now I'm thinking KISS. OK for you?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504)*

**Comment by whilei** [comment]
*[.circleci/config.yml, line 68 at r2](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L5k3kXWCNJFYjcZdXMG:-L5r2QTvASsLGVncyTyQ:bqgj1xg) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8dec486dd019b9438304276c5c3510fd1b175b57/.circleci/config.yml#L68)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

This is a cherry pick, right?
</blockquote></details>

Yep, rebase-ery I guess. Will remove.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504)*

**Comment by whilei** [comment]
*[.circleci/config.yml, line 68 at r2](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L5k3kXWCNJFYjcZdXMG:-L5r4rLc7R4a0nAerYnS:b-vo3luj) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8dec486dd019b9438304276c5c3510fd1b175b57/.circleci/config.yml#L68)):*
<details><summary><i>Previously, whilei (ia) wrote…</i></summary><blockquote>

Yep, rebase-ery I guess. Will remove.
</blockquote></details>

Fixed with merge upstream/master

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504)*

**Comment by whilei** [comment]
Heads up -- I've rebased and pushed again with the `--force`. Beware the dark side.

**Comment by whilei** [comment]
Not sure what's causing this -- passing locally for me.
```
--- FAIL: TestBcForkUncleTests (0.05s)
	block_test.go:56: ForkUncle: lastblockhash validation mismatch: want: 326971f0690f5557832ba60190f1f84010c4b18f4fb17e91d99e821e2cff2a2d, have: a307f8d0c778cdf3eda56bd70b0dbe217906c412de5ce0f21687e4805fefa575
FAIL
FAIL	github.com/ethereumproject/go-ethereum/tests	20.691s
```

**Comment by tzdybal** [comment]
For me problem is sometimes visible, but not always.

---

Reviewed 5 of 5 files at r3, 1 of 4 files at r4, 1 of 1 files at r5.
Review status: 18 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[logger/sys.go, line 26 at r2](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L5k8-zsxcsikqQ4b__y:-L5rpdck59_4ApGzHwcT:b-dbzu8r) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8dec486dd019b9438304276c5c3510fd1b175b57/logger/sys.go#L26)):*
<details><summary><i>Previously, whilei (ia) wrote…</i></summary><blockquote>

I think in the future it might be a nice-to-have feature, but for now I'm thinking KISS. OK for you?
</blockquote></details>

Absolutely.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-:-L5rpzK76Hcop0RClZB6:b9bk9l0)*

**Comment by tzdybal** [comment]
Seems like race-condition / issue with sleep in tests, or something like that. Investigating.

---

Review status: 18 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-:-L5rq_AA45YPSwE_X62w:b-7xe2by)*

**Comment by tzdybal** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504)*

**Comment by tzdybal** [comment]
:lgtm:
I have only some small questions, but nothing critical. 

---

Reviewed 1 of 4 files at r4, 23 of 23 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[eth/handler.go, line 322 at r6](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L7PZ7hO3infS10w-2MJ:-L7PZ7hO3infS10w-2MK:bouae4x) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8a051f3d99d6e444fb0b45384466eabfa4eba047/eth/handler.go#L322)):*
> ```Go
> func (pm *ProtocolManager) handleMsg(p *peer) (err error) {
> 	// Read the next message from the remote peer, and ensure it's fully consumed
> 	var unknownMessageCode uint64 = 666666
> ```

Maybe something less 'satanic', like `math.MaxUint64`? ;)

---

*[eth/protocol.go, line 68 at r6](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L7P_7kMDr-YJdFnZzKM:-L7P_7kMDr-YJdFnZzKN:bk344zi) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8a051f3d99d6e444fb0b45384466eabfa4eba047/eth/protocol.go#L68)):*
> ```Go
> )
> 
> func ProtocolMessageStringer(m uint) string {
> ```

Why not stinger running in `go generate` step? Just because of striping "Msg" from name?

---

*[p2p/message.go, line 100 at r6](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L7P_am46jdEExCchCgF:-L7P_am46jdEExCchCgG:b-eqdkxv) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8a051f3d99d6e444fb0b45384466eabfa4eba047/p2p/message.go#L100)):*
> ```Go
> // Send writes an RLP-encoded message with the given code.
> // data should encode as an RLP list.
> func Send(w MsgWriter, msgcode uint64, data interface{}) error {
> ```

Do we really need two variants of almost the same function? Can't `Send` return both error and size?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-:-L7PbDy446w4TmPX71yL:b72656z)*

**Comment by whilei** [comment]
@tzdybal I will address your comments and push changes tomorrow morn ;)

**Comment by whilei** [comment]
*[eth/protocol.go, line 68 at r6](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504#-L7P_7kMDr-YJdFnZzKM:-L7TAfAyCqEHAJC3oLrz:bhl4urg) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/8a051f3d99d6e444fb0b45384466eabfa4eba047/eth/protocol.go#L68)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Why not stinger running in `go generate` step? Just because of striping "Msg" from name?
</blockquote></details>

Because they're just `uint` constants and not typed. SGTY? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/504)*

**Pull request merged**
