### PR TITLE
Split chain config

### PR DESCRIPTION
**Pull request by tzdybal**
Ability to split chain config JSON into multiple files (using `"includes"` array).
 - every config file have the same structure - each file can contain partial config
 - nested including is supported
 - files are processed in order of listing in `"include"` array (it forms DFS traversal in case of nested includes)
 - include path can be relative or absolute

The default (mainnet and morden) config files refactored into 3 files:
 - `<chain>.json` - main config file
 - `<chain>_genesis.json` - genesis configuration
 - `<chain>_bootnodes.json` - bootnodes configuration ("bootstrap" field)

### CODE REVIEW

**Comment by r8d8** [comment]
Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---

*[core/config.go, line 421 at r1](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556#-L9k8nobAhuaAOHhLp4V:-L9k8nodAr3GoJ1DT70P:bpbfrag) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/aa1f1ab94403a314dabd743be56ee24b51394f49/core/config.go#L421)):*
> ```Go
> }
> 
> func parseExternalChainConfig(mainConfigFile string, open func(string) (io.ReadCloser, error)) (*SufficientChainConfig, error) {
> ```

Why do we need here lambda, and not just use `os.Open()` inside function body?

---

*[core/helpers.go, line 1 at r1](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556#-L9k7AKl9lu119g95F6Y:-L9k7AKl9lu119g95F6Z:b2ibfl) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/aa1f1ab94403a314dabd743be56ee24b51394f49/core/helpers.go#L1)):*
> ```Go
> // +build !windows
> ```

maybe not so abstract like `helpers`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556)*

**Comment by r8d8** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556)*

**Comment by tzdybal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/config.go, line 421 at r1](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556#-L9k8nobAhuaAOHhLp4V:-L9lDuMb8FCoQLnhbfLT:bge4lkh) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/aa1f1ab94403a314dabd743be56ee24b51394f49/core/config.go#L421)):*
<details><summary><i>Previously, r8d8 (Constantine) wrote…</i></summary><blockquote>

Why do we need here lambda, and not just use `os.Open()` inside function body?
</blockquote></details>

`os.Open` has different type. It's `func Open(string) (*File, error)`, and not `func(string) (io.ReadCloser, error)` (and this cannot be converted).  

---

*[core/helpers.go, line 1 at r1](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556#-L9k7AKl9lu119g95F6Y:-L9lESYA1_LBl26YONYx:bmcuqr6) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/aa1f1ab94403a314dabd743be56ee24b51394f49/core/helpers.go#L1)):*
<details><summary><i>Previously, r8d8 (Constantine) wrote…</i></summary><blockquote>

maybe not so abstract like `helpers`?
</blockquote></details>

Any ideas? ;)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556)*

**Comment by r8d8** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[core/config.go, line 421 at r1](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556#-L9k8nobAhuaAOHhLp4V:-L9nxTlxEfqY8tWalFoF:bl5fm3o) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/aa1f1ab94403a314dabd743be56ee24b51394f49/core/config.go#L421)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

`os.Open` has different type. It's `func Open(string) (*File, error)`, and not `func(string) (io.ReadCloser, error)` (and this cannot be converted).  
</blockquote></details>

I mean to remove this arg at all.

---

*[core/helpers.go, line 1 at r1](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556#-L9k7AKl9lu119g95F6Y:-L9nxZw433ywfFi1DKi4:b-np4ll6) ([raw file](https://github.com/ethereumproject/go-ethereum/blob/aa1f1ab94403a314dabd743be56ee24b51394f49/core/helpers.go#L1)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Any ideas? ;)
</blockquote></details>

`assets`. Imho, things like `helpers`, `utils` is a sign of bad granulation. But here it's separated into diferent files due to conditional compilation, so maybe there is no transparent name can fit it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ethereumproject/go-ethereum/556)*

**Pull request merged**
