### PR TITLE
CircleCI - complete MacOS workflow

### PR DESCRIPTION
**Pull request by tzdybal**
This PR contains working configuration.

<del>@splix please update the encrypted `gcloud-travis.json.enc` on this branch, and set `GCP_PASSWD` in CircleCI accordingly. Or maybe even better we should create new file for CircleCI for "backward compatibility" and modify `deploy.sh`. </del>

### CODE REVIEW

**Comment by tzdybal** [comment]
@splix I prepared everything for deployment with both Travis and CircleCI. Please create a `gcloud-circleci.json.enc` file in this branch and configure the `GCP_PASSWD` environment variable on CircleCI project configuration.

**Comment by tzdybal** [comment]
Please re-review - simple job turned into workflow with cache and workspace to save some time.

**Comment by whilei** [comment]
Re-reviewed ✅ 
Still LGTM. The linux OOM is annoying, since we'll be riding two horses at once (Travis and Circle) for a while until resolved, but IMO better to move forward post haste to get some of these bugfixes in and the next release with them out. 

I guess we'll need to merge this PR as a first priority to get the other PRs in, since they're failing/blocked because of no tests on Circle currently

**Comment by tzdybal** [comment]
I agree, to merge this ASAP, and then reconfigure gitbub project (remove the requirement on travis mac build) - but I don't have admin privileges.

**Comment by whilei** [comment]
@splix Can you please remove the Travis OSX build requirement once we get this PR in?

**Comment by splix** [comment]
I've disabled requirement for Travis

**Pull request merged**
