### PR TITLE
ECIP-1015 GasReprice fork

### PR DESCRIPTION
**Pull request by splix**
ECIP-1015 GasReprice

changes applied from EF Geth ethereum/go-ethereum@64af2aa

### CODE REVIEW

**Comment by splix** [comment]
I don’t think it well tested though. all unit test from EF geth are passing, but we don’t have any integration tests for our chain yet (EF has one integration test, but it contains TheDAO Fork state changes, we can’ reuse it). 

Someone should prepare json with test data (who wants?). See `/tests/files/BlockchainTests/TestNetwork/bcEIP150Test.bak.json` for example

**Comment by splix** [comment]
As we follow Semantic Versioning, this release must be 3.0.0. Because we introduce incompatible changes (basically every new fork is a new MAJOR version)

**Comment by splix** [comment]
@ericsomdahl @elaineo @mikeyb @whatisgravity please review

**Comment by realcodywburns** [comment]
The in params/utils.go: MainNetHomesteadGasRepriceBlock = big.NewInt(2463000) >> 25000000 this is what globally sets the homstead block. theu did not add any daoFork logic in the selection

**Comment by splix** [comment]
@ericsomdahl feel free to merge PR if you'll approve these changes

**Comment by splix** [comment]
@ericsomdahl good catch! fixed

**Comment by ericsomdahl** [comment]
I agree with @splix regarding the testing, especially circling back and creating a proper full blockchain test.  Given the urgency I think this must do for now

**Comment by elaineo** [comment]
Looks like it's already merged, but i can add testdata for this.

**Pull request merged**
