### PR TITLE
[WIP] Pluggable consensus

### PR DESCRIPTION
**Pull request by r8d8**

### CODE REVIEW

**Comment by whilei** [comment]
ooh boy it's a big one

**Comment by whilei** [comment]
These import diffs are annoying, but right. 

@r8d8 can you make a separate PR with just those import sortings and we can pull that in quick before this to clean up the review?

**Comment by 5chdn** [comment]
#648 superseded this, didn't it?

**Comment by thomasmodeneis** [comment]
> #648 superseded this, didn't it?

It looks like it did

**Pull request closed without merging**
