### PR TITLE
initialize /docs

### PR DESCRIPTION
**Pull request by whilei**
> problem: documentation
> init: docs/ for gitbook documentation
> 
> This creates in-repo documentation intialized
> from existing JSON-RPC documentation on the Github wiki.

---

geth-gitbook-wiki

---

Directory structure:
```
~/gocode/src/github.com/ethereumproject/go-ethereum/docs docs-gitbook-json-rpc
$ tree
.
├── README.md
├── SUMMARY.md
├── json-rpc
│   ├── default-params.md
│   ├── endpoints.md
│   ├── methods
│   │   ├── db
│   │   │   ├── db.md
│   │   │   ├── getHex.md
│   │   │   ├── getString.md
│   │   │   ├── putHex.md
│   │   │   └── putString.md
│   │   ├── debug
│   │   │   ├── accountExist.md
│   │   │   └── debug.md
│   │   ├── eth
│   │   │   ├── accounts.md
│   │   │   ├── blockNumber.md
│   │   │   ├── call.md
│   │   │   ├── chainId.md
│   │   │   ├── coinbase.md
│   │   │   ├── compileLLL.md
│   │   │   ├── compileSerpent.md
│   │   │   ├── compileSolidity.md
│   │   │   ├── estimateGas.md
│   │   │   ├── eth.md
│   │   │   ├── gasPrice.md
│   │   │   ├── getBalance.md
│   │   │   ├── getBlockByHash.md
│   │   │   ├── getBlockByNumber.md
│   │   │   ├── getBlockTransactionCountByHash.md
│   │   │   ├── getBlockTransactionCountByNumber.md
│   │   │   ├── getCode.md
│   │   │   ├── getCompilers.md
│   │   │   ├── getFilterChanges.md
│   │   │   ├── getFilterLogs.md
│   │   │   ├── getLogs.md
│   │   │   ├── getStorageAt.md
│   │   │   ├── getTransactionByBlockHashAndIndex.md
│   │   │   ├── getTransactionByBlockNumberAndIndex.md
│   │   │   ├── getTransactionByHash.md
│   │   │   ├── getTransactionCount.md
│   │   │   ├── getTransactionReceipt.md
│   │   │   ├── getUncleByBlockHashAndIndex.md
│   │   │   ├── getUncleByBlockNumberAndIndex.md
│   │   │   ├── getUncleCountByBlockHash.md
│   │   │   ├── getUncleCountByBlockNumber.md
│   │   │   ├── getWork.md
│   │   │   ├── hashrate.md
│   │   │   ├── mining.md
│   │   │   ├── newBlockFilter.md
│   │   │   ├── newFilter.md
│   │   │   ├── newPendingTransactionFilter.md
│   │   │   ├── protocolVersion.md
│   │   │   ├── sendRawTransaction.md
│   │   │   ├── sendTransaction.md
│   │   │   ├── sign.md
│   │   │   ├── submitHashrate.md
│   │   │   ├── submitWork.md
│   │   │   ├── syncing.md
│   │   │   └── uninstallFilter.md
│   │   ├── geth
│   │   │   └── getAddressTransactions.md
│   │   ├── net
│   │   │   ├── listening.md
│   │   │   ├── net.md
│   │   │   ├── peerCount.md
│   │   │   └── version.md
│   │   ├── shh
│   │   │   ├── addToGroup.md
│   │   │   ├── getFilterChanges.md
│   │   │   ├── getMessages.md
│   │   │   ├── hasIdentity.md
│   │   │   ├── newFilter.md
│   │   │   ├── newGroup.md
│   │   │   ├── newIdentity.md
│   │   │   ├── post.md
│   │   │   ├── shh.md
│   │   │   ├── uninstallFilter.md
│   │   │   └── version.md
│   │   └── web3
│   │       ├── clientVersion.md
│   │       ├── sha3.md
│   │       └── web3.md
│   ├── outputs.md
│   └── usage.md
└── jsre
    ├── caveats.md
    ├── how-to.md
    ├── integration.md
    ├── interactive-use.md
    ├── management-apis.md
    ├── methods
    │   ├── admin
    │   │   ├── addPeer.md
    │   │   ├── admin.md
    │   │   ├── datadir.md
    │   │   ├── exportChain.md
    │   │   ├── getContractInfo.md
    │   │   ├── importChain.md
    │   │   ├── nodeInfo.md
    │   │   ├── peers.md
    │   │   ├── register.md
    │   │   ├── registerUrl.md
    │   │   ├── saveInfo.md
    │   │   ├── setSolc.md
    │   │   ├── sleep.md
    │   │   ├── sleepBlocks.md
    │   │   ├── startNatSpec.md
    │   │   ├── startRPC.md
    │   │   ├── startWS.md
    │   │   ├── stopNatSpec.md
    │   │   ├── stopRPC.md
    │   │   └── stopWS.md
    │   ├── debug
    │   │   ├── accountExist.md
    │   │   ├── debug.md
    │   │   ├── dumpBlock.md
    │   │   ├── getBlockRlp.md
    │   │   ├── metrics.md
    │   │   ├── printBlock.md
    │   │   ├── seedHash.md
    │   │   └── setHead.md
    │   ├── eth
    │   │   ├── eth.md
    │   │   ├── pendingTransactions.md
    │   │   ├── resend.md
    │   │   └── sign.md
    │   ├── geth
    │   │   ├── getAddressTransactions.md
    │   │   └── geth.md
    │   ├── interfaces
    │   │   ├── additional-interfaces.md
    │   │   ├── inspect.md
    │   │   ├── loadScript.md
    │   │   ├── net.md
    │   │   ├── shh.md
    │   │   └── web3.md
    │   ├── miner
    │   │   ├── makeDAG.md
    │   │   ├── miner.md
    │   │   ├── setEtherbase.md
    │   │   ├── setExtra.md
    │   │   ├── setGasPrice.md
    │   │   ├── start.md
    │   │   ├── startAutoDAG.md
    │   │   ├── stop.md
    │   │   └── stopAutoDAG.md
    │   ├── personal
    │   │   ├── listAccounts.md
    │   │   ├── newAccount.md
    │   │   ├── personal.md
    │   │   └── unlockAccount.md
    │   └── txpool
    │       ├── status.md
    │       └── txpool.md
    ├── non-interactive-use.md
    └── timers.md

19 directories, 139 files

```

Runnable html output (eg. `docs-website/_target/html/go-ethereum`):

[go-ethereum.html.tar.gz](https://github.com/ethereumproject/go-ethereum/files/2019214/go-ethereum.html.tar.gz)

----

This is an initial pass. The only job of this PR is to establish a format for documentation going forward, and to resituate existing documentation from the wiki [JSON-RPC](https://github.com/ethereumproject/go-ethereum/wiki/JSON-RPC) and [JSRE](https://github.com/ethereumproject/go-ethereum/wiki/JavaScript-Console) within the in-repo Gitbook-friendly format.

This is the script I used to help migrate the existing wiki pages to proposed directory system. https://gist.github.com/whilei/30ee9cd46745c20b9725511d2d5ee161

### CODE REVIEW

**Comment by splix** [comment]
what about moving rpc api docs a separate repo? we talked about it, as it's a standard api, works for emerald also

**Comment by whilei** [comment]
I think there's a lot of value in both, actually.

I think it's important to keep documentation close to the source code. This keeps "the map" close to "the territory," which is important for establishing a development workflow that keeps the two in sync. (A PR for an API change to geth would otherwise need to coordinate with _another_ PR in a separate repo... doable, but awkward).

I _also_ think it's important to keep "same-domain" documentations close (eg. RPC API). This encourages consistency in formatting, presentation, and updates. 

Since we're relying on a script to build and publish Gitbook documentation to the web... what if we added a feature to that script to publish changes to a Github repository? Something like

```shell
# add flag './build.sh -u' to enable/toggle rpc-docs repo updates?
# ... or could just add another script to separate concerns, then run
# ./build.sh && ./rpc-docs.sh

git clone https://github.com/ETCDEVTeam/rpc-docs

# grab known constant '/docs' subdir from each project
for project in  _sources/*; do
	rsync $project/docs/json-rpc rpc-docs/$project/docs/json-rpc
done
git --work-tree=rpc-docs/$project --git-dir=rpc-docs/$project/.git add . && commit -m "auto update rpc docs from relevant repos"
git --work-tree=rpc-docs/$project --git-dir=rpc-docs/$project/.git push origin
rm -rf ./rpc-docs
```

**Comment by splix** [comment]
For RPC API it's a general documentation. Geth is one of implementations, but I agree it will be nice to cover what is the difference in geth implementation of standard

**Comment by whilei** [comment]
And it's important that ETCDEVTeam doesn't take "ownership" (`ETCDEVTeam/` namespace) of the documentation. The project belongs to the community, and the documentation should too.

**Comment by splix** [comment]
As we're going to have a manual for geth, how are we going to split these two? different directories?

**Comment by whilei** [comment]
Yea -- I thought we could use something like
- `/docs/json-rpc`
- `/docs/user-guide`
- `/docs/cli`
- `/docs/code`

**Comment by splix** [comment]
right, so we create a separate doc that not geth specific. because we can't avoid making docs for our projects because there're other projects

**Comment by lostinblue** [comment]
im sorry i'm confused by this

**Pull request closed without merging**
