### PR TITLE
Vendorin

### PR DESCRIPTION
**Pull request by pascaldekloe**
Dependency cleanups

### CODE REVIEW

**Comment by splix** [comment]
Hm, so with vendoring all dependencies are committed to source tree?

**Comment by pascaldekloe** [comment]
Almost all of'm. I'd like todo the remaining ones in separate pull requests.


Op 22 feb. 2017 7:13 p.m. schreef "Igor Artamonov" <notifications@github.com

**Comment by splix** [comment]
I mean, is it a standard practice to put foreign code in go? I just don't know. How people deal with license conflicts at this case? like LGPL for example, is it compatible with it? 

I understand that for out case (GPL3) it doesn't matter, but how people develop commercial software at this case?

**Comment by pascaldekloe** [comment]
Yes that's standard for Go. No tools needed. Instead of compiled code you
import source in dedicated directories. Same license rules apply.


Op 22 feb. 2017 7:30 p.m. schreef "Igor Artamonov" <notifications@github.com
>:

I mean, is it a standard practice to put foreign code in go? I just don't
know. How people deal with license conflicts at this case? like LGPL for
example, is it compatible with it?

I understand that for out case (GPL3) it doesn't matter, but how people
develop commercial software at this case?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereumproject/go-ethereum/pull/140#issuecomment-281758436>,
or mute the thread

**Pull request merged**
