### PR TITLE
Pluggable consensus (develop cache)

### PR DESCRIPTION
**Pull request by r8d8**

### CODE REVIEW

**Comment by eosclassicteam** [comment]
So you guys are implementing POA consensus on classic geth?? Cool 👍

**Comment by r8d8** [comment]
@eosclassicteam, you are right

**Comment by eosclassicteam** [comment]
@r8d8 Is clique engine compatible with original go-ethereum? Is there any testnet running with it??

**Comment by r8d8** [comment]
@eosclassicteam, yes it is

**Comment by r8d8** [comment]
Moved to https://github.com/ethereumproject/go-ethereum/pull/648

**Pull request closed without merging**
