### PR TITLE
Make SputnikVM support morden testnet

### PR DESCRIPTION
**Pull request by sorpaas**
This fixed a missing chain config for starting nonce to support morden
testnet. Please update your sputnikvm-ffi repo if you wish to test out
this patch.

### CODE REVIEW

**Comment by whilei** [comment]
Although building from vendor will create a minor chore for upgrading with future svm/svm-ffi updates, I'm keen to agree with @tzdybal to keep the dependencies controlled and reproducible. The change to build scripts could be included with #449.

**Comment by sorpaas** [comment]
Please review @ethereumproject/etcdev-team

**Comment by whilei** [comment]
@tzdybal https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.1359#L49

solution may be `git push upstream --delete v4.2.1-netgo`?

**Comment by sorpaas** [comment]
Okay now the TravisCI is finally passed. I'm going to merge this.

**Pull request merged**
