### PR TITLE
Changes in EF Geth Release 1.4.13

### PR DESCRIPTION
**Pull request by splix**

### CODE REVIEW

**Comment by splix** [comment]
@elaineo @ericsomdahl @whatisgravity please review

**Comment by elaineo** [comment]
should this be a release? (changes look reasonable, but i'll pull and test tonight)

**Comment by splix** [comment]
@elaineo it's changes from EF, I think we should add them to our code (same for 1.4.14 PR, and later I'll add changes from 1.4.15)

**Comment by mikeyb** [comment]
Compiles fine but getting errors on the tests with this branch, will look into errors further and see what I can find.

```
~/p/go-ethereum ❯❯❯ go test ./tests                                                                                    ef-release/1.4.13 ✭
# _/home/miko/projects/go-ethereum/tests
tests/state_test_util.go:100: statedb.MarkStateObjectDirty undefined (type *state.StateDB has no field or method MarkStateObjectDirty)
tests/state_test_util.go:139: statedb.MarkStateObjectDirty undefined (type *state.StateDB has no field or method MarkStateObjectDirty)
tests/util.go:111: undefined: state.NewObject
tests/util.go:112: cannot use common.Big(account.Balance) (type *big.Int) as type string in field value
tests/util.go:113: cannot use "github.com/ethereumproject/go-ethereum/crypto".Keccak256(code) (type []byte) as type string in field value
tests/vm_test_util.go:106: statedb.MarkStateObjectDirty undefined (type *state.StateDB has no field or method MarkStateObjectDirty)
tests/vm_test_util.go:157: statedb.MarkStateObjectDirty undefined (type *state.StateDB has no field or method MarkStateObjectDirty)
tests/vm_test_util.go:242: undefined: params.DiehardBlock
tests/vm_test_util.go:242: undefined: params.ExplosionBlock
FAIL	_/home/miko/projects/go-ethereum/tests [build failed]
```

**Comment by mikeyb** [comment]
We seem to have a lot of changes out of sync with the upstream repo.  Not sure we can merge big changes like this currently or in the future as the code bases are becoming much different within the same methods.

This seems like we will need to implement the fixes manually to match our code base and not theirs.

**Comment by splix** [comment]
@mikeyb thank you for the report. Did you manage to fix this tests?

**Comment by mikeyb** [comment]
I did not.  I am at a conference yesterday and today so time is very limited and I am behind on paid work so I probably wont get a real stab at this for days.  We have some fundamental differences in core/state/ from the ETHF repo and trying to merge any of their current changes through [1.4.15 PR](https://github.com/ethereumproject/go-ethereum/pull/49) will [fail tests](https://github.com/ethereumproject/go-ethereum/pull/46#issuecomment-251380630) along with errors when interacting with the blockchain [as seen here](https://gist.github.com/mikeyb/7c85d6245f7c26ba79c715d437d3a15c)

**Comment by splix** [comment]
Ok, sure, we need to fix that. @mikeyb, can you take care of this?

**Comment by mikeyb** [comment]
Looks like we need to cherry-pick another ETHF commit [as noted here](https://github.com/ethereumproject/go-ethereum/pull/36#issuecomment-251675143)

@whatisgravity is going to take a look at it but if for some reason he doesn't have time I can definitely work on getting all the missing merges together, but I definitely wont have time today or tomorrow.

**Comment by splix** [comment]
Oh, it's here as [28f2b02], but it seems to be different from original. Maybe it's because it has conflicts and was merged manually

**Comment by elaineo** [comment]
@splix @mikeyb I was at a work event the last 2 days, but I am back now and will work on fixing tests today.

**Comment by elaineo** [comment]
@mikeyb I'm not getting any errors here. It looks like some of your errors were because you didn't have updates merged from develop.

**Pull request merged**
