### PR TITLE
Drop JIT

### PR DESCRIPTION
**Pull request by pascaldekloe**
The VM does not need configuration. Also drops several debugging components. Use standard tooling to trace execution instead.

### CODE REVIEW

**Comment by dulanov** [comment]
Is your goal to remove all that possible? )))

**Comment by pascaldekloe** [comment]
As a rule @dulanov. :joy: Every line must have a good reason to be there.

**Comment by pascaldekloe** [comment]
Travis is still highly unstable since the Amazon fallout yesterday. Also our test suite fails about 1 out of 10 attempts. The same commit succeeded over here: https://travis-ci.org/pascaldekloe/go-ethereum/builds/206611228
There's another patch coming up for this pull request...

**Comment by splix** [comment]
hm, but if fails with errors like:
```
# github.com/ethereumproject/go-ethereum/core/vm/runtime
core/vm/runtime/env.go:61: undefined: vm.Config
core/vm/runtime/env.go:69: too many arguments in call to vm.New
# github.com/ethereumproject/go-ethereum/cmd/evm
cmd/evm/main.go:122: undefined: vm.Config
cmd/evm/main.go:209: undefined: vm.Config
cmd/evm/main.go:218: too many arguments in call to vm.New
```

**Comment by pascaldekloe** [comment]
Retry with #146.

**Pull request closed without merging**
