### PR TITLE
Update block_validator.go

### PR DESCRIPTION
**Pull request by bragcustom**
Proposal to remove exponential bomb.

### CODE REVIEW

**Comment by whatisgravity** [comment]
Has this been tested on a private network? I have not yet reviewed the code but I'm curious to know.

**Comment by obscuren** [comment]
https://github.com/ethereumproject/go-ethereum/commit/2af3ea164147133afaca90c684891e5d89227ccf#commitcomment-18397979

**Comment by obscuren** [comment]
This is going to fail horribly as is. Please know what you're doing before attempting to fiddle with the core code.

**Comment by obscuren** [comment]
I also suggest you write tests for this, including tests in the `tests` repo. Changing protocol without tests (either Go tests or consensus JSON tests) is not recommended.

**Comment by realcodywburns** [comment]
Sage advice. It would be suicide to dump a core algo update with out solid testing. Need 'roadmap'  with verifiable stage gates.

**Comment by whatisgravity** [comment]
I agree with @obscuren this is not an adequate solution. A change of this magnitude needs tests, I recommend starting with tests. It is also very beneficial to provide reasoning for your proposal.

**Pull request closed without merging**
