### PR TITLE
 p2p: use closest(s3) instead of closest(self) in lookup(self) 

### PR DESCRIPTION
**Pull request by sorpaas**
Merge after #524.

This implements countermeasure 4 in
https://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf

### CODE REVIEW

**Comment by sorpaas** [comment]
@r8d8 This is the order: #523 -> #524 -> #525

**Comment by sorpaas** [comment]
Can someone restart the Appveyor test?

**Comment by whilei** [comment]
We can wait for the tests to auto-restart after merging previous "parent" PRs and then updating this branch respectively, or?

**Comment by sorpaas** [comment]
@r8d8 @whilei Tests have passed.

**Pull request merged**
