### PR TITLE
Build Status

### PR DESCRIPTION
**Pull request by pascaldekloe**
* let Travis CI do the testing
* test compile fix
* batch organisation (issue #124)

### CODE REVIEW

**Comment by ericsomdahl** [comment]
Is the ultimate intent to move everything over to Travis CI and away from TeamCity?

**Comment by pascaldekloe** [comment]
I'd very much like that @ericsomdahl.  There's too much stuff going on on those build servers. Also the links from the README lead to a login page. That's not how we welcome developers.

**Comment by ericsomdahl** [comment]
@pascaldekloe -- I don't disagree with that assessment given that I am the keeper of those servers 😄 .   

I would say that our usage of TeamCity is driven primarily by the fact Jetbrains gave us free licenses for all of their dev and CI tools.  That and familiarity.

**Comment by splix** [comment]
I guess we can use both, TC can be still useful for some tests

**Comment by ericsomdahl** [comment]
@pascaldekloe would you like an account on the TC system?  I locked down new account registrations a while ago because bots were registering themselves, probably hoping to find a forum to spam.

**Comment by pascaldekloe** [comment]
No thanks @ericsomdahl. If we can all agree on a more minimalistic setup then I'd like to drop he TC links, `build/ci.go`, etc.

**Comment by ericsomdahl** [comment]
we inherited ci.go from upstream, and their build system is vastly more complicated than ours :)  Simplification would be much appreciated

**Pull request merged**
